const TYPES = {
  GOOGLE: {
    ANALYTICS_VISITS: 'analytics-visits'
  },
  FACEBOOK: {
    PAGE_LIKES: 'page-likes',
    IG_FOLLOWERS: 'ig-followers'
  },
  TWITTER: {
    FOLLOWERS: 'followers'
  },
  MAILCHIMP: {
    SUBSCRIBERS: 'subscribers'
  },
  WOOCOMMERCE: {
    SALES: 'sales'
  },
  EDD: {
    EARNINGS: 'earnings'
  },
  WORDPRESS: {
    METRIC: 'metric'
  },
  WORDPRESSORG: {
    PLUGIN: 'plugin',
    PORTFOLIO: 'portfolio'
  },
  PLAUSIBLE: {
    TRAFFIC: 'traffic'
  },
}

const SERVICES = {
  GOOGLE: 'google',
  FACEBOOK: 'facebook',
  TWITTER: 'twitter',
  MAILCHIMP: 'mailchimp',
  WOOCOMMERCE: 'woocommerce',
  EDD: 'edd',
  WORDPRESS: 'wordpress',
  WORDPRESSORG: 'wordpressorg',
  PLAUSIBLE: 'plausible'
}

const DAILY_REFRESH_WIDGETS = [
  `${SERVICES.EDD}-${TYPES.EDD.EARNINGS}`,
  `${SERVICES.WOOCOMMERCE}-${TYPES.WOOCOMMERCE.SALES}`,
  `${SERVICES.MAILCHIMP}-${TYPES.MAILCHIMP.SUBSCRIBERS}`,
  `${SERVICES.FACEBOOK}-${TYPES.FACEBOOK.IG_FOLLOWERS}`,
  `${SERVICES.FACEBOOK}-${TYPES.FACEBOOK.PAGE_LIKES}`,
  `${SERVICES.TWITTER}-${TYPES.TWITTER.FOLLOWERS}`,
  `${SERVICES.WORDPRESS}-${TYPES.WORDPRESS.METRIC}`,
  `${SERVICES.WORDPRESSORG}-${TYPES.WORDPRESSORG.PLUGIN}`,
  `${SERVICES.WORDPRESSORG}-${TYPES.WORDPRESSORG.PORTFOLIO}`,
  `${SERVICES.PLAUSIBLE}-${TYPES.PLAUSIBLE.TRAFFIC}`
];

const NO_FORCE_REFRESH_WIDGETS = [
  `${SERVICES.GOOGLE}-${TYPES.GOOGLE.ANALYTICS_VISITS}`
];

export { TYPES, SERVICES, DAILY_REFRESH_WIDGETS, NO_FORCE_REFRESH_WIDGETS }
